update to fix undefined reference to '__waddbytes'
git-svn-id: https://svn.osgeo.org/grass/grass/branches/releasebranch_5_5@125 15284696-431f-4ddb-bdfa-cd5b030d7da7